rule_files:
  - "./rules/*.yml"

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 3s
    scrape_timeout: 1s
    static_configs:
    - targets:
      - kr-web-dev1:9100
      labels:
        region: KR
        disk: SATA
        environment: dev
    - targets:
      - kr-web-prod1:9100
      labels:
        region: KR
        disk: SSD
        environment: prod
    - targets:
      - us-web-prod1:9100
      labels:
        region: US
        disk: SSD
        environment: prod
