scrape_configs:
  - job_name: 'node_exporter'
    follow_redirects: false
    scrape_interval: 5s
    scrape_timeout: 1s

    static_configs:
      - targets:
          - kr-web-dev1:9100
        labels:
          region: KR
          disk: SATA
          env: dev
      - targets:
          - kr-web-prod1:9100
        labels:
          region: KR
          disk: SSD
          env: prod
      - targets:
          - us-web-prod1:9100
        labels:
          region: US
          disk: SSD
          env: prod

    relabel_configs:
      - source_labels: ['__address__']
        regex: '(.*):(.*)'
        replacement: '${1}'
        target_label: 'instance'

      - source_labels: ['__address__']
        target_label: 'port'
        regex: '(.*):(.*)'
        replacement: '${2}'
